config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'events#index'

  resources :events do
    resources :comments, only: [:create, :destroy]
    resources :subscriptions, only: [:create, :destroy]
    resources :photos, only: [:create, :destroy]
    post :show, on: :member
  end

  resources :users, only: [:show, :edit, :update]
end

app/models/photo.rb
class Photo < ApplicationRecord
  belongs_to :event
  belongs_to :user

  validates :event, presence: true
  validates :user, presence: true

  mount_uploader :photo, PhotoUploader

  scope :persisted, -> { where "id IS NOT NULL" }
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  before_action :set_event, only: [:create, :destroy]
  before_action :set_photo, only: [:destroy]
  before_action :set_new_photo, only: [:create]

  def create
    unless current_user.present?
      return redirect_to @event, alert: I18n.t('activerecord.controllers.photos.current_user_error')
    end

    @new_photo.user = current_user

    if  @new_photo.photo.url.present? && @new_photo.save
      notify_new_photo(@event, @new_photo)

      redirect_to @event, notice: I18n.t('activerecord.controllers.photos.created')
    else
      redirect_to @event, alert: I18n.t('activerecord.controllers.photos.error')
    end
  end

  def destroy
    message = {notice: I18n.t('activerecord.controllers.photos.destroyed')}

    if current_user_can_edit?(@photo)
      @photo.destroy
    else
      message = {alert: I18n.t('activerecord.controllers.photos.error')}
    end

    redirect_to @event, message
  end

  private
  # Так как фотография — вложенный ресурс, то в params[:event_id] рельсы
  # автоматически положает id события, которому принадлежит фотография
  # найденное событие будет лежать в переменной контроллера @event
  def set_event
    @event = Event.find(params[:event_id])
  end

  # Получаем фотографию из базы стандартным методом find
  def set_photo
    @photo = @event.photos.find(params[:id])
  end

  # При создании новой фотографии мы получаем массив параметров photo
  # c единственным полем (оно тоже называется photo)
  def photo_params
    params.fetch(:photo, {}).permit(:photo)
  end

  def notify_new_photo(event, photo)
    all_emails = (event.subscriptions.map(&:user_email) + [event.user.email] - [photo.user.email]).uniq

    all_emails.each do |mail|
      EventMailer.photo(photo, event, mail).deliver_now
    end
  end

  def set_new_photo
    @new_photo = @event.photos.build(photo_params)
  end
end

app/views/photos/_form.html.erb
<%= form_for [@event, photo], html: { multipart: true } do |f| %>
    <%= render partial: 'partials/form_errors', locals: {model: photo} %>

    <div class="form-group">
      <%= f.label :photo %>
      <%= f.file_field :photo %>
    </div>

    <div class="actions">
      <%= f.submit 'Загрузить', class: 'btn btn-primary' %>
    </div>
<% end %>

app/views/photos/_photo.html.erb
<div class="event-photo">
  <% image_title = "Добавил #{render partial: 'users/user', object: photo.user}" %>
  <% if photo.photo.url.present? %>
  <%= link_to image_tag(photo.photo.thumb.url), photo.photo.url, data: {
      lightbox: "event", title: image_title, gallery: 'event-photos'
  } %>
  <% end %>
  <% if photo.photo.url.present? && current_user_can_edit?(photo) %>
    <%= link_to(fa_icon('trash'), event_photo_path(photo.event, photo),
                method: :delete, data: {confirm: t('photos.photo.del_confirmation')})
    %>
  <% end %>
</div>